### ISSUE TITLE
 cargo install --path . is causing 7 build errors.

### ISSUE THREAD

**Issue by BartStodola** [reujab/silver#86]
just cloned the silver repo

1. cargo build
2. cargo install --path .

is causing build errors: 
  Installing silver v2.0.0 (C:\dev\repos\silver)
    Updating crates.io index
   Compiling silver v2.0.0 (C:\dev\repos\silver)
error[E0432]: unresolved import `clap::Clap`
 --> src\cli.rs:1:9

any ideas?

**Comment by drewcassidy** [comment]
Im having the same issue trying to compile it. Its like there's an unresolved dependency

**Comment by typecasto** [comment]
Getting the same thing with `cargo install silver`, have been for a while now. At least a month or so I think, but I might be wrong.

**Comment by typecasto** [comment]
Looking through the log, while it hasn't installed correctly since 87180ea926028dd4fba9ebafa1f012b62865ab33, the current error (the 7 errors) seem to be introduced in 6098b2ecc5c1a222b33de76990436670233b3715. My guess is that something upstream changed, with clap, and that's causing it to fail, not any recent commit, since this was 2020/08 that this commit was introduced. I'm pretty stumped. Seems to be an error with clap, but I can't tell much beyond that.

---

Here's the script I made to determine this, it stops when a commit compiles. Run this in the fish shell. It's pretty slow, so you can verify my results by just checking out 87180ea926028dd4fba9ebafa1f012b62865ab33 and then running it. It should fail once, then succeed. 
```fish
while not docker run -t --init --rm rust bash -c "git clone https://github.com/reujab/silver.git; cd silver; git checkout "(git rev-parse HEAD)"; cargo install --path ."
      git checkout HEAD~1;
      echo "Giving you a minute to quit...";
      sleep 5;
  end
```
